### ISSUE TITLE
Docker Image Not Starting

### ISSUE THREAD

**Issue by MysticRyuujin** [GridPlus/lattice-connect#5]
Commit: `f49427fd6a733fab34c432b167ed5b4a1174aa5c`

I cloned the repo, issued `npm run docker-build` then saved the image and loaded the image on my docker host then tried to run it with `docker run -dit --name lattice-connect -p 8000:80 -p 1883:1883 lattice-connect:1.0` and got the below error:

```
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2][ERROR] Script not found: /usr/src/app/dist/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lattice-connect@0.1.1 start: `npx pm2 start dist/index.js --name lattice-connect --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lattice-connect@0.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

```
npm version
{
  npm: '6.14.11',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.15.5',
  openssl: '1.1.1i',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.18',
  zlib: '1.2.11'
}
```

**Comment by MysticRyuujin** [comment]
New Error:

I ran this:
```bash
git pull
npm run docker-build
```

Commit: `9ce703de53aa30a060f85f89a0f40d40937216cb`
```
docker logs lattice-connect

> lattice-connect@0.1.1 start-docker /usr/src/app
> node dist/index.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/usr/src/app/dist/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lattice-connect@0.1.1 start-docker: `node dist/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lattice-connect@0.1.1 start-docker script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by alex-miller-0** [comment]
Sorry, `docker-start` was deprecated. It is now removed in ` 00475e4`. You will need to run `docker-run`, though I would recommend pulling the latest.
